export const dashboardFilterFields = [
  'codUnidad',
  'edificio',
  'unidad',
  'estado',
  'nombre',
  'cedula',
  'telefono',
  'correo',
  'metraje',
  'precio',
  'inicial',
  'inicialDolar',
  'pagado',
  'adeudado',
  'formaPago',
  'banco',
  'fechaCompletaInicial',
  'fechaInicioVaciados',
  'fechaEntrega',
  'fechaEntregaInspeccion',
  'fechaLegal',
  'fechaGobierno',
  'fechaMicelaneos',
  'fechaInspeccion1',
  'fechaInspeccion2',
  'fechaFormaPago',
  'enInspeccion',
  'legal',
  'titulo',
  'saldo',
  'entregada',
  'descargadaDGII'
];

export const dashboardFilterLabels: Record<string, string> = {
  codUnidad: 'Codigo Unidad',
  edificio: 'Edificio',
  unidad: 'Unidad',
  estado: 'Estado',
  nombre: 'Cliente',
  cedula: 'Cedula',
  telefono: 'Telefono',
  correo: 'Correo',
  metraje: 'Metraje',
  precio: 'Precio',
  inicial: 'Inicial',
  inicialDolar: 'Inicial USD',
  pagado: 'Pagado',
  adeudado: 'Adeudado',
  formaPago: 'Forma de Pago',
  banco: 'Banco',
  fechaCompletaInicial: 'Fecha Inicial Completa',
  fechaInicioVaciados: 'Fecha Inicio Vaciados',
  fechaEntrega: 'Fecha Entrega',
  fechaEntregaInspeccion: 'Fecha Entrega Inspeccion',
  fechaLegal: 'Fecha Legal',
  fechaGobierno: 'Fecha Gobierno',
  fechaMicelaneos: 'Fecha Miscelaneos',
  fechaInspeccion1: 'Fecha Inspeccion 1',
  fechaInspeccion2: 'Fecha Inspeccion 2',
  fechaFormaPago: 'Fecha Forma de Pago',
  enInspeccion: 'En Inspeccion',
  legal: 'Legal',
  titulo: 'Titulo',
  saldo: 'Saldado',
  entregada: 'Entregada',
  descargadaDGII: 'Descargada DGII'
};

export const dashboardFilterTypes: Record<string, 'text' | 'boolean' | 'date' | 'number'> = {
  codUnidad: 'text',
  edificio: 'text',
  unidad: 'text',
  estado: 'text',
  nombre: 'text',
  cedula: 'text',
  telefono: 'text',
  correo: 'text',
  metraje: 'number',
  precio: 'number',
  inicial: 'number',
  inicialDolar: 'number',
  pagado: 'number',
  adeudado: 'number',
  formaPago: 'text',
  banco: 'text',
  fechaCompletaInicial: 'date',
  fechaInicioVaciados: 'date',
  fechaEntrega: 'date',
  fechaEntregaInspeccion: 'date',
  fechaLegal: 'date',
  fechaGobierno: 'date',
  fechaMicelaneos: 'date',
  fechaInspeccion1: 'date',
  fechaInspeccion2: 'date',
  fechaFormaPago: 'date',
  iniciadoVaciados: 'boolean',
  enInspeccion: 'boolean',
  inspeccion1: 'boolean',
  inspeccion2: 'boolean',
  legal: 'boolean',
  gobierno: 'boolean',
  micelaneos: 'boolean',
  titulo: 'boolean',
  saldo: 'boolean',
  entregada: 'boolean',
  descargadaDGII: 'boolean'
};
